#!/usr/bin/env python3
"""Extracts per-lesson Learning Objectives from every
module_decks/*/INSTRUCTOR_LECTURE_NOTES.md into skills.json — the source of
truth for what specific skill a reading is actually preparing a Fellow for,
one level more granular than taxonomy.json's broad category tags.

Deliberately NOT derived by guessing at what a reading "should" cover —
every objective here is the deck author's own stated learning objective for
that lesson, so a reading claiming to prep for one is a checkable claim,
not a vibe.

Re-run this any time a new deck lands in module_decks/ — it always
regenerates skills.json from scratch, so it's safe to run repeatedly.

    python3 extract_skills.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
DECKS_DIR = ROOT / "module_decks"
LESSON_HEADER = re.compile(r"^# Instructor Prep: (.+)$", re.M)
MODULE_LINE = re.compile(r"^\*Module \d+: (.+)\*$", re.M)


def slugify(text):
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return re.sub(r"-{2,}", "-", s)


def extract_bullets(block, heading):
    m = re.search(rf"^## {re.escape(heading)}\s*\n((?:- .+\n?)+)", block, re.M)
    if not m:
        return []
    return [line[2:].strip() for line in m.group(1).splitlines() if line.startswith("- ")]


def parse_deck(path):
    text = path.read_text(encoding="utf-8")
    headers = list(LESSON_HEADER.finditer(text))
    lessons = []
    for i, h in enumerate(headers):
        start = h.end()
        end = headers[i + 1].start() if i + 1 < len(headers) else len(text)
        block = text[start:end]
        title = h.group(1).strip()
        mod_match = MODULE_LINE.search(block)
        module_name = mod_match.group(1).strip() if mod_match else path.parent.name
        objectives_text = extract_bullets(block, "Learning Objectives")
        prereqs_text = extract_bullets(block, "Prerequisites")
        lesson_id = slugify(title)
        lessons.append({
            "lesson_id": lesson_id,
            "title": title,
            "module_source": path.parent.name,
            "module_name": module_name,
            "prerequisites_text": prereqs_text,
            "objectives": [
                {"id": f"{lesson_id}__obj{n}", "text": obj}
                for n, obj in enumerate(objectives_text, start=1)
            ],
        })
    return lessons


def main():
    all_lessons = []
    for deck_path in sorted(DECKS_DIR.glob("*/INSTRUCTOR_LECTURE_NOTES.md")):
        all_lessons.extend(parse_deck(deck_path))

    seen_ids = {}
    for lesson in all_lessons:
        if lesson["lesson_id"] in seen_ids:
            print(f"[warn] duplicate lesson_id '{lesson['lesson_id']}' "
                  f"({lesson['module_source']} vs {seen_ids[lesson['lesson_id']]}) — "
                  "check for a repeated lesson title across decks")
        seen_ids[lesson["lesson_id"]] = lesson["module_source"]

    out = {
        "_comment": "Generated by extract_skills.py from module_decks/*/INSTRUCTOR_LECTURE_NOTES.md "
                    "Learning Objectives. Do not hand-edit — re-run the script instead. "
                    "module_source/module_name are for traceability only; never surface them "
                    "in a reading's visible text (no module numbers/names in reading content).",
        "lessons": all_lessons,
    }
    (ROOT / "skills.json").write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    total_objectives = sum(len(l["objectives"]) for l in all_lessons)
    print(f"Wrote skills.json — {len(all_lessons)} lessons, {total_objectives} objectives")


if __name__ == "__main__":
    main()
